### ISSUE TITLE
Copy and paste

### ISSUE THREAD

**Issue by ctnlaring** [papyros/terminal-app#17]
You can't copy and paste or right click at all

**Comment by iBelieve** [comment]
`Ctrl+Shift+C/V` doesn't work for you? Works correctly for me.

**Comment by ctnlaring** [comment]
Oh. I didn't know you had to use a shift. Is this documented somewhere?

**Comment by zigapk** [comment]
It is actually default for (almost) all terminal apps.

**Comment by iBelieve** [comment]
As @zigapk, using shift is standard in every terminal app I know on Linux. Check out #5 for how we want to improve on this.
