### ISSUE TITLE
Cannot open terminal

### ISSUE THREAD

**Issue by libf-de** [papyros/terminal-app#18]
When i open papyros terminal nothing happens. I found this in the log output:

```
QQmlApplicationEngine failed to load component
qrc:/qml/main.qml:22 module "QMLTermWidget" is not installed
```

Latest papyros shell/terminal from papyros-testing repo, on Thinkpad X220 (Intel HD 3000).

**Comment by zigapk** [comment]
@iBeliever it is probably a repository issue, since it seems that qml-term-widget doesn't get installed (properly).

**Comment by libf-de** [comment]
Fixed it by installing `qmltermwidget`. Seems like that dependency is missing
