### ISSUE TITLE
Smart copy/paste

### ISSUE THREAD

**Issue by iBelieve** [papyros/terminal-app#5]
This would be an awesome feature to have: https://plus.google.com/u/1/+DanielForé/posts/PhtmZQs98vW.

**Comment by timsueberkrueb** [comment]
+1, that'd be great!

**Comment by ricardomv** [comment]
i wouldn't mess with it much if there is a bug we could disable the fastest way to stop a program, and i think this would be more annoying than useful (for me at least). And don't forget we have to support other apps.

**Comment by IdrissDimson** [comment]
i'd loooove this feature

**Comment by iBelieve** [comment]
@ricardomv What I've done is included a setting to disable it for people who find it annoying
