### ISSUE TITLE
Roboto font

### ISSUE THREAD

**Issue by zigapk** [papyros/terminal-app#6]
When setting terminal session font.family to Roboto, font is somehow offset. Anyhow Roboto should probably be used to match material design guidelines. And because I looks great.

**Comment by iBelieve** [comment]
@zigapk Have you tried Roboto Mono? That would be the monospaced version of Roboto.

**Comment by VirusKA** [comment]
^this

**Comment by zigapk** [comment]
How exactly can I declare it? Because <a href="https://github.com/papyros/qml-material/tree/develop/modules/Material/fonts/roboto">here</a> I can't find any mono version.

EDIT: Okay I imported it from ttf file, but there still is some offset and I get this error: `Using an unsupported variable-width font in the terminal.  This may produce display errors.` I will try to google it out but if anybody has any idea he is welcome to help.

**Comment by VirusKA** [comment]
variable-width font?

**Comment by dominicap** [comment]
If you are looking for the Roboto Mono font its right here https://www.google.com/fonts/download?kit=rqQ1zSE-ZGCKVZgew-A9dofD-WQWLbF4rYwcBGowFYY

**Comment by ricardomv** [comment]
i don't have any issues with the `ttf-roboto-mono` package installed from AUR

**Comment by IdrissDimson** [comment]
@ricardomv did you test out that roboto mono package with the terminal?

**Comment by zigapk** [comment]
@ricardomv you tried it in terminal app? If so, you can add it to dependencies and commit changes.

**Comment by zigapk** [comment]
True, @ricardomv was right. Using ttf-roboto-mono from AUR works fine. Closing the issue with next commit.
