### ISSUE TITLE
Warn when running commands with sudo

### ISSUE THREAD

**Issue by iBelieve** [papyros/terminal-app#8]
See https://plus.google.com/u/0/112026213399155142823/posts/hS499SgDRwY?cfem=1

![tabs-gnome-elementary](https://cloud.githubusercontent.com/assets/3230912/12272509/745e7910-b926-11e5-8ee5-173279b02e1c.png)

**Comment by iBelieve** [comment]
We'll also want a way to hide that message. While we could just put a "Do not show again" checkbox in the prompt, I think a better option would be to put it in settings. Doing that will make it harder for a user to blindly ignore the warning and prevent it from showing again.

**Comment by IdrissDimson** [comment]
@iBeliever i like you idea for an implementation to this enhancement. It'll save many non-programmers from doing something dumb

**Comment by iBelieve** [comment]
![Warning](http://i.imgur.com/XeX9AXn.png)

**Comment by IdrissDimson** [comment]
BRUHHHHH that's beautiful!
